name: Update Floating Version Tags

on:
  release:
    types: [published]

jobs:
  update-semver:
    name: Update Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Semver
        uses: ./.
